### ISSUE TITLE
Information request reagarding "kegg_mudule.py" "make_pathway.py" "pathway_presence.py"

### ISSUE THREAD

**Issue by stefcamp** [ctSkennerton/KeggPathways#1]
Dear Connor T. Skennerton,
I would like to ask if it is possible to use one of the scripts reported in this repository to assess the completeness of KEGG modules starting from a list of KEGG codes IDs and if you can provide minimum information regarding the procedure to follow.
I tried to use MetQy software but I did not obtain successful results.
Sincerely
--
Stefano Campanaro
Department of Biology
University of Padova

**Comment by ctSkennerton** [comment]
I never actually got this working properly, and it should not be used. I should make a readme that says this.
